In [1]:
import pandas as pd
import numpy as np
import numpy as np

In [3]:
data = pd.read_csv('crsp_compustat_combined.csv')
data.head()

/var/folders/nq/svc2nf551n74zpynk96y1b7w0000gn/T/ipykernel_77250/2909798904.py:1: DtypeWarning: Columns (6,7,10,20,23,25,73) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('crsp_compustat_combined.csv')

,PERMNO,DATE,index,NAMEENDT,SHRCD,EXCHCD,SICCD,NCUSIP,TICKER,COMNAM,...,conm,Book_to_Market,prcc_f,revt,invt,LINKDT,LINKENDDT,LINKPRIM,LIID,LINKTYPE
0,10000,1986-10-31,10,NaN,10.0,3.0,3990.0,68391610,OMFGA,OPTIMUM MANUFACTURING INC,...,OPTIMUM MANUFACTURING -CL A,0.145026,0.75,1.026,0.512,1986-01-07,1987-06-30,P,01,LU
1,10000,1986-11-30,11,NaN,10.0,3.0,3990.0,68391610,OMFGA,OPTIMUM MANUFACTURING INC,...,NaN,NaN,NaN,NaN,NaN,1986-01-07,1987-06-30,NaN,NaN,NaN
2,10000,1986-12-31,12,1987-03-09,10.0,3.0,3990.0,68391610,OMFGA,OPTIMUM MANUFACTURING INC,...,NaN,NaN,NaN,NaN,NaN,1986-01-07,1987-06-30,NaN,NaN,NaN
3,10000,1987-01-31,13,NaN,10.0,3.0,3990.0,68391610,OMFGA,OPTIMUM MANUFACTURING INC,...,NaN,NaN,NaN,NaN,NaN,1986-01-07,1987-06-30,NaN,NaN,NaN
4,10000,1987-02-28,14,NaN,10.0,3.0,3990.0,68391610,OMFGA,OPTIMUM MANUFACTURING INC,...,NaN,NaN,NaN,NaN,NaN,1986-01-07,1987-06-30,NaN,NaN,NaN

In [4]:
data.shape

(2711830, 75)

In [5]:
data.groupby('PERMNO').size()

PERMNO
10000      8
10001    374
10002    314
10003    103
10005     55
        ...
93430     15
93433     72
93434    150
93435     17
93436    156
Length: 22266, dtype: int64

In [6]:
data_sub = data[data['PERMNO'] == 10026]
data_sub

,PERMNO,DATE,index,NAMEENDT,SHRCD,EXCHCD,SICCD,NCUSIP,TICKER,COMNAM,...,conm,Book_to_Market,prcc_f,revt,invt,LINKDT,LINKENDDT,LINKPRIM,LIID,LINKTYPE
2882,10026,1986-09-30,4720,NaN,11.0,3.0,2050.0,46603210,JJSF,J & J SNACK FOODS CORP,...,J & J SNACK FOODS CORP,0.485264,8.75,25.419,1.195,1986-02-04,2024-04-30,P,01,LU
2883,10026,1986-10-31,4721,NaN,11.0,3.0,2050.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN
2884,10026,1986-11-30,4722,NaN,11.0,3.0,2050.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN
2885,10026,1986-12-31,4723,NaN,11.0,3.0,2050.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN
2886,10026,1987-01-31,4724,NaN,11.0,3.0,2050.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3324,10026,2023-07-31,5162,NaN,11.0,3.0,2052.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN
3325,10026,2023-08-31,5163,NaN,11.0,3.0,2052.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN
3326,10026,2023-09-30,5164,NaN,11.0,3.0,2052.0,46603210,JJSF,J & J SNACK FOODS CORP,...,J & J SNACK FOODS CORP,0.288119,163.65,1558.829,171.539,1986-02-04,2024-04-30,P,01,LU
3327,10026,2023-10-31,5165,NaN,11.0,3.0,2052.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN
3328,10026,2023-11-30,5166,NaN,11.0,3.0,2052.0,46603210,JJSF,J & J SNACK FOODS CORP,...,NaN,NaN,NaN,NaN,NaN,1986-02-04,2024-04-30,NaN,NaN,NaN

In [7]:
# get all the numerical columns
X = data_sub.select_dtypes(include=[np.number])
X = X.dropna(axis=1)
X

,PERMNO,index,SHRCD,EXCHCD,PERMCO,ISSUNO,HEXCD,HSICCD,BIDLO,ASKHI,...,CFACPR,CFACSHR,ALTPRC,RETX,vwretd,vwretx,ewretd,ewretx,sprtrn,MV
2882,10026,4720,11.0,3.0,7976,10433,3,2052.0,8.75000,11.75000,...,4.0,4.0,8.75000,-0.166667,-0.079020,-0.081272,-0.059071,-0.060184,-0.085439,2.553250e+04
2883,10026,4721,11.0,3.0,7976,10433,3,2052.0,7.62500,9.75000,...,4.0,4.0,9.75000,0.114286,0.049305,0.046860,0.023777,0.022803,0.054729,2.845050e+04
2884,10026,4722,11.0,3.0,7976,10433,3,2052.0,9.50000,10.25000,...,4.0,4.0,10.25000,0.051282,0.015093,0.010874,-0.006263,-0.007526,0.021477,2.990950e+04
2885,10026,4723,11.0,3.0,7976,10433,3,2052.0,9.75000,10.25000,...,4.0,4.0,9.75000,-0.048780,-0.026387,-0.029056,-0.034609,-0.036117,-0.028288,2.845050e+04
2886,10026,4724,11.0,3.0,7976,10433,3,2052.0,9.75000,15.75000,...,4.0,4.0,15.75000,0.615385,0.128499,0.126927,0.117565,0.116677,0.131767,4.595850e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3324,10026,5162,11.0,3.0,7976,10433,3,2052.0,154.14000,164.64000,...,1.0,1.0,160.32001,0.012377,0.035624,0.034678,0.043309,0.042322,0.031139,3.092573e+06
3325,10026,5163,11.0,3.0,7976,10433,3,2052.0,159.37000,177.17000,...,1.0,1.0,162.13000,0.011290,-0.020605,-0.022263,-0.052542,-0.054050,-0.017716,3.127488e+06
3326,10026,5164,11.0,3.0,7976,10433,3,2052.0,162.09000,173.88000,...,1.0,1.0,163.64999,0.009375,-0.047390,-0.048859,-0.055443,-0.057553,-0.048719,3.163682e+06
3327,10026,5165,11.0,3.0,7976,10433,3,2052.0,150.84000,162.99001,...,1.0,1.0,156.61000,-0.043019,-0.028867,-0.029858,-0.060887,-0.062055,-0.021980,3.027585e+06
3328,10026,5166,11.0,3.0,7976,10433,3,2052.0,158.49001,169.57001,...,1.0,1.0,164.55000,0.050699,0.092057,0.090041,0.080251,0.078328,0.089179,3.182726e+06

In [15]:
# X.columns
y = X['RET']
X = X.drop(columns=['RET'])

# PCA

In [16]:
X.shape

(447, 25)

In [17]:
from sklearn.decomposition import PCA

In [18]:
pca = PCA(n_components=10)
X_reduced_pca = pca.fit_transform(X)
X_reduced_pca.shape

(447, 10)

In [19]:
pca.explained_variance_ratio_

array([9.99961114e-01, 2.98974873e-05, 8.98673088e-06, 1.36916751e-09,
       6.38460404e-11, 1.02586762e-11, 6.08058648e-12, 1.39754533e-13,
       2.18593179e-14, 1.16779808e-14])

In [20]:
pca.singular_values_

array([2.24032800e+07, 1.22500369e+05, 6.71615822e+04, 8.28988189e+02,
       1.79014016e+02, 7.17572377e+01, 5.52449755e+01, 8.37535072e+00,
       3.31236627e+00, 2.42105095e+00])

Get the weights of every stock in the principal components.

Then we can use it for returns